### ISSUE TITLE
Uncaught TypeError: Cannot read property 'strategies' of undefined

### ISSUE THREAD

**Issue by CavalcanteLeo** [SmartsquareGmbH/nuxt-auth-auto-refresh#1]
```js
  plugins: [
    ...
    { src: 'node_modules/nuxt-auth-auto-refresh/dist/index.js', ssr: false },
  ],


  modules: [
    ['@nuxtjs/dotenv', { filename: process.env.FILENAME }],
    '@nuxtjs/axios',
    '@nuxtjs/auth',
    '@nuxtjs/pwa',
   ....
  ],

  auth: {
    strategies: {
      local: {
        scheme: 'refresh',
        refreshToken: {
          maxAge: 60 * 60,
        },
        endpoints: {
          refresh: {
            url: '/refresh-token',
            method: 'get',
            propertyName: 'jwt',
          },
          login: { url: 'login', method: 'post', propertyName: 'token' },
          user: { url: 'users/profile', method: 'get', propertyName: false },
          logout: false,
        },
        tokenName: 'authorization',
      },
    },

    redirect: {
      login: '/entrar',
      logout: '/entrar',
      callback: '/entrar',
      home: '/templates',
    },
  },
```

<img width="533" alt="Captura de Tela 2020-11-26 às 04 21 27" src="https://user-images.githubusercontent.com/1735944/100319746-eba92080-2f9e-11eb-8f55-4082db0bec4d.png">

**Comment by rubengees** [comment]
Please add the plugin to the `plugins` section of nuxt-auth (see here: https://github.com/SmartsquareGmbH/nuxt-auth-auto-refresh#usage).

Also, this plugin only works with nuxt-auth-next and not the v4 version of nuxt-auth.

**Comment by rubengees** [comment]
Closing for now. Please open a new issue if you have another question or problem.

**Comment by jirbel** [comment]
Already managed to fix this issue. Must change `({ $auth }: { $auth: Auth })` to `(context: { $auth: Auth })` and use context.$auth instead. Dont know why is $auth undefined in time of load.
